function [x,util]=ablrconga(RAD,CLN,labels,cvcvp,param) % used for FCM (ablation experiment)

nvars = width(RAD);
popsize = 200; % population size
elitecount = ceil(0.05*popsize);
xoverfraction = 0.85; % (popsize - elitecount)/(popsize-elitecount);
clear util;
util = OurUtilHandle;
util.param = param;
util.generation = 0;

options = optimoptions('ga', ... % gamultiobj ga
  'PopulationType', 'bitstring', ...
  'PopulationSize', popsize, ...
  'UseVectorized', true, ...
  'MaxGenerations', 104, ...
  'PlotFcn', 'gaplotbestf', ... % gaplotpareto gaplotbestf gaplotspread {[]} gaplotrankhist  
  'FunctionTolerance', 1e-6, ...  
  'CreationFcn', @(nvars,f,options)ourcreation(options.PopulationSize,RAD,CLN,labels,cvcvp,util), ...   
  'MutationFcn',@(parents,options,nvars,FitnessFcn,state,unused,POP) ourmutation(parents,POP,util), ...
  'EliteCount', elitecount, ...
  'CrossoverFraction', xoverfraction, ...
  'CrossoverFcn', @(parents,options,nvars,FitnessFcn,unused,POP) ourcrossover(parents,POP,util), ...
  'display','off' ...
  ); 
  
x=ga(@(X)ablrconfitness(X,RAD,CLN,labels,cvcvp,util),nvars,[],[],[],[],[],[],[],options);